// TODO:
//   - Hex float/int parsing
//   - = signs between [[ in multiline comments and strings -> [===[String]===]
//   - <close> and <const> attributes in local assignments -> local a <const> = ...
#[derive(Clone, Debug)]
pub enum TokenKind {
    Identifier(String),
    LiteralString(String),
    LiteralFloat(f64),
    LiteralInt(i64),
    LiteralBoolean(bool),
    LiteralNil,
    Assign,
    Plus,
    Minus,
    Mul,
    Div,
    FloorDiv,
    Mod,
    Pow,
    Eq,
    Ne,
    Le,
    Ge,
    Lt,
    Gt,
    And,
    Or,
    Not,
    Len,
    Concat,
    BitAnd,
    BitOr,
    BitXor,
    Shl,
    Shr,
    Comma,
    Semicolon,
    Varargs,
    Colon,
    DoubleColon,
    ParenOpen,
    ParenClose,
    BracketsOpen,
    BracketsClose,
    CurlyBracesOpen,
    CurlyBracesClose,
    KeywordLocal,
    KeywordFunction,
    KeywordIf,
    KeywordThen,
    KeywordElseIf,
    KeywordElse,
    KeywordEnd,
    KeywordReturn,
    KeywordWhile,
    KeywordDo,
    KeywordBreak,
    KeywordRepeat,
    KeywordUntil,
    KeywordGoto,
    KeywordFor,
    Eof,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub line: usize,
    pub column: usize,
}
